### ISSUE TITLE
problem in accessing the kshortestpath service 

### ISSUE THREAD

**Issue by grv1207** [Caleydo/neo4j-kshortestpaths-plugin#4]
Hi after following the steps for building the project and storing jar file in neo4j plugin directory and then clicking  http://localhost:7474/db/data/ext/KShortestPaths/graphdb/kShortestPaths

I get the following error:
```
No such ServerPlugin: "KShortestPaths"
PluginLookupException
	At org.neo4j.server.plugins.PluginManager.extension (PluginManager.java:114)
	At org.neo4j.server.plugins.PluginManager.describe (PluginManager.java:123)
	At org.neo4j.server.rest.web.ExtensionService.describeGraphDatabaseExtension (ExtensionService.java:318)
	At org.neo4j.server.rest.web.ExtensionService.getGraphDatabaseExtensionDescription (ExtensionService.java:169)
	At java.lang.reflect.Method.invoke (Method.java:497)
	At org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch (TransactionalRequestDispatcher.java:147)
	At org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter (AuthorizationEnabledFilter.java:122)
	At org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter (CollectUserAgentFilter.java:69)
	At java.lang.Thread.run (Thread.java:745)
```
what should I do?

**Comment by sgratzl** [comment]
you have to register this unnamed extension within the neo4j configuration

**Comment by grv1207** [comment]
Could you provide me detail steps for registering this extension within in neo4j as this is the first time I'm using neo4j
presently I'm writing this line in my .config file
dbms.unmanaged_extension_classes=org.caleydo.neo4j.plugins.kshortestpaths=/org.caleydo.neo4j.plugins.kshortestpaths
When I start my server I get the following error.
Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@60b00118' was successfully initialized, but failed to start. Please see attached cause exception.

**Comment by priyank-mehta** [comment]
Registering your Extension:
in neo4j.conf: (see last line for reference)
dbms.unmanaged_extension_classes=org.caleydo.neo4j.plugins.kshortestpaths=/caleydo/kshortestpaths

 @grv1207 
(Please do not cross post in other issue)

**Comment by grv1207** [comment]
@priyank-mehta I'm still receiving same error after adding dbms.unmanaged_extension_classes=org.caleydo.neo4j.plugins.kshortestpaths=/caleydo/kshortestpaths in my config file
 {
Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@60b00118' was successfully initialized, but failed to start. Please see attached cause exception.
}

**Comment by grv1207** [comment]
So apparently I'm able to open service in Ubuntu
