### ISSUE TITLE
Rest API call [POST] giving BadInputException

### ISSUE THREAD

**Issue by priyank-mehta** [Caleydo/neo4j-kshortestpaths-plugin#6]
As given in README file, I queried the API endpoint 

> [GET] http://localhost:7474/db/data/ext/KShortestPaths/graphdb/kShortestPaths

provided output:

> {'extends': 'graphdb', 'name': 'kShortestPaths', 'parameters': [{'type': 'node', 'optional': False, 'name': 'source', 'description': 'Source node of the path'}, {'type': 'node', 'optional': False, 'name': 'target', 'description': 'Target node of the path'}, {'type': 'integer', 'optional': False, 'name': 'k', 'description': 'The max number of paths to retrieve'}, {'type': 'string', 'optional': True, 'name': 'costFunction', 'description': 'Javascript cost function to determine the cost of an edge'}, {'type': 'string', 'optional': True, 'name': 'constraints', 'description': 'constraints'}], 'description': 'get the k shortest paths from source to target'}

Expected Parameters are : Source (Node) , Target(Node) , K(integer) as mandatory parameters

My problem is how do I ,**using REST API**, provide Node type object as input? It should be NodeID or it should accept a standard JSON Object as returned by Neo4j GetNode REST API Call.

This makes the plugin unusable outside Java environment. I am using **Neo4j with Python** and hence **cannot use this plugin**

**Comment by grv1207** [comment]
Hi, how did you configured the extension in config file?
I did this
dbms.unmanaged_extension_classes=org.caleydo.neo4j.plugins.kshortestpaths=/org.caleydo.neo4j.plugins.kshortestpaths
but my instance doesnt start. I know I made some mistake but could you help me rectify it?

**Comment by priyank-mehta** [comment]
I think I am facing issues due to lack of proper documentation. Guys can you please update the readme on how to configure and use the plugin

Thanks

**Comment by grv1207** [comment]
what solution you found @priyank-mehta ?
